apiVersion: apps/v1
kind: Deployment
metadata:
  name:  container-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  container-app
  template:
    metadata:
      labels:
        app: container-app:1.0
    spec:
      containers:
      - name: container-app:1.0
        image: kuhu2701/container-app:1.0
        ports:
        - containerPort: 5000
